/**
 * @file coronachat_status.h
 * @author Ofri Snir
 * @date 10.04.2020
 * @beirf All return value of coronachat functions.
 */

#ifndef __CORONACHAT_CORONACHAT_STATUS_H__
#define __CORONACHAT_CORONACHAT_STATUS_H__

enum coronachat_status {
    CORORNACHAT_STATUS_UNINITIALIZED = -1,
    CORORNACHAT_STATUS_SUCCESS = 0,

    /* linked_list */
    CORORNACHAT_STATUS_LINKED_LIST_INIT_INVALID_PARAMETERS = 0x1000,
    CORORNACHAT_STATUS_LINKED_LIST_INIT_ALLOC_LIST_CONTEXT_FAILURE,

    CORORNACHAT_STATUS_LINKED_LIST_FREE_INVALID_PARAMETERS,

    CORORNACHAT_STATUS_LINKED_LIST_APPEND_INVALID_PARAMETERS,

    CORORNACHAT_STATUS_LINKED_LIST_PREPEND_INVALID_PARAMETERS,

    CORORNACHAT_STATUS_LINKED_LIST_GET_NEXT_INVALID_PARAMETERS,

    CORORNACHAT_STATUS_LINKED_LIST_GET_PREV_INVALID_PARAMETERS,

    CORORNACHAT_STATUS_LINKED_LIST_REMOVE_INVALID_PARAMETERS,

    CORORNACHAT_STATUS_LINKED_LIST_ADD_NODE_INVALID_PARAMETERS,
    CORORNACHAT_STATUS_LINKED_LIST_ADD_NODE_INVALID_NODE_POSITION,

    CORORNACHAT_STATUS_LINKED_LIST_CREATE_NODE_INVALID_PARAMETERS,
    CORORNACHAT_STATUS_LINKED_LIST_CREATE_NODE_ALLOC_NODE_FAILURE,

    CORORNACHAT_STATUS_LINKED_LIST_DESTROY_NODE_INVALID_PARAMETERS,
    CORORNACHAT_STATUS_LINKED_LIST_DESTROY_NODE_INVALID_FREEING_METHOD,

    CORORNACHAT_STATUS_LINKED_LIST_GET_NODE_INVALID_PARAMETERS,
    CORORNACHAT_STATUS_LINKED_LIST_GET_NODE_INVALID_NODE_POSITION,

    /* ui */
    CORORNACHAT_STATUS_UI_GET_MESSAGE_READ_FAILED = 0x1100,
    CORORNACHAT_STATUS_UI_GET_MESSAGE_PRINT_INPUT_FAILED, 
    CORORNACHAT_STATUS_UI_GET_MESSAGE_REFRESH_FAILED,
    CORORNACHAT_STATUS_UI_GET_MESSAGE_INVALID_PARAMETERS,

    CORORNACHAT_STATUS_UI_PRINT_INPUT_BOX_INVALID_PARAMETERS,
    CORORNACHAT_STATUS_UI_PRINT_INPUT_BOX_REFRESH_FAILED, 
    CORORNACHAT_STATUS_UI_PRINT_INPUT_BOX_PRINT_FAILED,

    CORORNACHAT_STATUS_UI_DESTROY_SCREEN_CLEAR_FAILED,
    CORORNACHAT_STATUS_UI_DESTROY_SCREEN_ENDWIN_FAILED,

    CORORNACHAT_STATUS_UI_INIT_SCREEN_INITSCR_FAILED,
    CORORNACHAT_STATUS_UI_INIT_SCREEN_NOECHO_FAILED,

    CORORNACHAT_STATUS_UI_PRINT_ALL_LINES_PRINT_FAILED,
    CORORNACHAT_STATUS_UI_PRINT_ALL_LINES_REFRESH_FAILED,
    CORORNACHAT_STATUS_UI_PRINT_ALL_LINES_CLEAR_FAILED,
    CORORNACHAT_STATUS_UI_PRINT_ALL_LINES_INVALID_PARAMETERS,

};

#define CORONACHAR_TEST_FAILURE(__status) (CORORNACHAT_STATUS_SUCCESS != __status)

#define BEST_EFFORT_UPDATE_STATUS(__new_status, __status) \
do { \
    if ((CORORNACHAT_STATUS_UNINITIALIZED != __status) && (CORORNACHAT_STATUS_SUCCESS != __status)) { \
        __status = __new_status; \
    } \
} while(0)

#endif /* !__CORONACHAT_CORONACHAT_STATUS_H__ */