/**
 * @file coronachat_status.h
 * @author Ofri Snir
 * @date 10.04.2020
 * @beirf All return value of coronachat functions.
 */

#ifndef __CORONACHAT_CORONACHAT_STATUS_H__
#define __CORONACHAT_CORONACHAT_STATUS_H__

enum coronachat_status {
    CORORNACHAT_STATUS_UNINITIALIZED = -1,
    CORORNACHAT_STATUS_SUCCESS = 0,

    /* linked_list */
    CORORNACHAT_STATUS_LINKED_LIST_INIT_INVALID_PARAMETERS = 1000,
    CORORNACHAT_STATUS_LINKED_LIST_INIT_ALLOC_LIST_CONTEXT_FAILURE,

    CORORNACHAT_STATUS_LINKED_LIST_FREE_INVALID_PARAMETERS,

    CORORNACHAT_STATUS_LINKED_LIST_APPEND_INVALID_PARAMETERS,

    CORORNACHAT_STATUS_LINKED_LIST_PREPEND_INVALID_PARAMETERS,

    CORORNACHAT_STATUS_LINKED_LIST_GET_NEXT_INVALID_PARAMETERS,

    CORORNACHAT_STATUS_LINKED_LIST_GET_PREV_INVALID_PARAMETERS,

    CORORNACHAT_STATUS_LINKED_LIST_REMOVE_INVALID_PARAMETERS,

    CORORNACHAT_STATUS_LINKED_LIST_ADD_NODE_INVALID_PARAMETERS,
    CORORNACHAT_STATUS_LINKED_LIST_ADD_NODE_INVALID_NODE_POSITION,

    CORORNACHAT_STATUS_LINKED_LIST_CREATE_NODE_INVALID_PARAMETERS,
    CORORNACHAT_STATUS_LINKED_LIST_CREATE_NODE_ALLOC_NODE_FAILURE,

    CORORNACHAT_STATUS_LINKED_LIST_DESTROY_NODE_INVALID_PARAMETERS,
    CORORNACHAT_STATUS_LINKED_LIST_DESTROY_NODE_INVALID_FREEING_METHOD,

    CORORNACHAT_STATUS_LINKED_LIST_GET_NODE_INVALID_PARAMETERS,
    CORORNACHAT_STATUS_LINKED_LIST_GET_NODE_INVALID_NODE_POSITION,

    /* network_utils */
    CORORNACHAT_STATUS_NETWORK_UTILS_SETUP_LISTENER_INVALID_PARAMETERS = 2000,
    CORORNACHAT_STATUS_NETWORK_UTILS_SETUP_LISTENER_GETADDRINFO_FAILURE,
    CORORNACHAT_STATUS_NETWORK_UTILS_SETUP_LISTENER_BIND_LISTENER_FAILURE,
    CORORNACHAT_STATUS_NETWORK_UTILS_SETUP_LISTENER_LISTEN_FAILURE,

    CORORNACHAT_STATUS_NETWORK_UTILS_ACCEPT_CONNECTION_INVALID_PARAMETERS,
    CORORNACHAT_STATUS_NETWORK_UTILS_ACCEPT_CONNECTION_ALLOC_CLIENT_ADDRESS_BUFFER_FAILURE,
    CORORNACHAT_STATUS_NETWORK_UTILS_ACCEPT_CONNECTION_ACCEPT_FAILURE,

    CORORNACHAT_STATUS_NETWORK_UTILS_CONNECT_INVALID_PARAMETERS,
    CORORNACHAT_STATUS_NETWORK_UTILS_CONNECT_GETADDRINFO_FAILURE,
    CORORNACHAT_STATUS_NETWORK_UTILS_CONNECT_CONNECT_FAILURE,

    CORONACHAT_STATUS_NETWORK_UTILS_SEND_MESSAGE_INVALID_PARAMETERS,
    CORONACHAT_STATUS_NETWORK_UTILS_SEND_MESSAGE_SEND_FAILURE,

    CORONACHAT_STATUS_NETWORK_UTILS_RECEIVE_MESSAGE_INVALID_PARAMETERS,
    CORONACHAT_STATUS_NETWORK_UTILS_RECEIVE_MESSAGE_IOCTL_FAILURE,
    CORONACHAT_STATUS_NETWORK_UTILS_RECEIVE_MESSAGE_ALLOC_MESSAGE_FAILURE,
    CORONACHAT_STATUS_NETWORK_UTILS_RECEIVE_MESSAGE_RECV_FAILURE,

    CORORNACHAT_STATUS_NETWORK_UTILS_ITERATE_ADDRESS_LIST_INVALID_PARAMETERS,

    CORORNACHAT_STATUS_NETWORK_UTILS_BIND_TO_ADDRESS_INVALID_PARAMETERS,
    CORORNACHAT_STATUS_NETWORK_UTILS_BIND_TO_ADDRESS_SOCKET_FAILURE,
    CORORNACHAT_STATUS_NETWORK_UTILS_BIND_TO_ADDRESS_SETSOCKOPT_FAILURE,
    CORORNACHAT_STATUS_NETWORK_UTILS_BIND_TO_ADDRESS_BIND_FAILURE,

    CORORNACHAT_STATUS_NETWORK_UTILS_CONNECT_TO_ADDRESS_INVALID_PARAMETERS,
    CORORNACHAT_STATUS_NETWORK_UTILS_CONNECT_TO_ADDRESS_SOCKET_FAILURE,
    CORORNACHAT_STATUS_NETWORK_UTILS_CONNECT_TO_ADDRESS_CONNECT_FAILURE,
};

#define CORONACHAR_TEST_FAILURE(__status) (CORORNACHAT_STATUS_SUCCESS != __status)

#define BEST_EFFORT_UPDATE_STATUS(__new_status, __status) \
do { \
    if ((CORORNACHAT_STATUS_UNINITIALIZED != __status) && (CORORNACHAT_STATUS_SUCCESS != __status)) { \
        __status = __new_status; \
    } \
} while(0)

#endif /* !__CORONACHAT_CORONACHAT_STATUS_H__ */